### PR TITLE
idea for new look

### PR DESCRIPTION
**Pull request by u-an-i**
based on https://github.com/albar965/littlenavmap/discussions/672 I finally come around providing the idea ready to be pulled.

I started a completely new aviation-inspired look half a year ago but didn't continue it and think I might have lost those files.

Thus here mainly paragraph look adjustments to make information easier and faster graspable - at least for me, as well as inspired by my curiosity the un-hover showing of the background-image.

See a video view here: https://uani.de/support/lnm-website-ui-idea.mp4

### CODE REVIEW

**Comment by albar965** [comment]
Thanks looking good. :+1: 
Like the closed box for scrolling.

Two things, though: 
The front text is somehow a two column text but the text goes across the two columns.
I think the animation on hover/leave might irritate people. Maybe the whole text block should not disappear but rather shrink a bit instead. Just an idea.

**Comment by u-an-i** [comment]
I'm ready to perform changes.
About your items:
1. the columns currently apply per paragraph. Would you rather have them apply per block (so 2 long columns instead of n * 2 short columns) (I don't know yet whether this works with CSS only) or would you prefer no columns?
2. yes this is the idea of mine which might irritate. The purpose is to have the interesting background be completely visible as a possibility. I implement a shrinking.

**Comment by u-an-i** [comment]
Hi @albar965 , 

I removed the "unhover full image view", I didn't have a good idea to have something not possibly rather irritating.
I also set 1 column only because otherwise HTML would have to be modified which I didn't want to burden you with.

When looking through the contact page I noticed the links color wasn't good discernible from the text for me this I changed the link color to a darker CSS "deepskyblue".

I also reordered the CSS as SCSS and commented it for you to be able to easier change parts.

If you have something particular in mind for your web presentation, put it forward! I'll see what i can realise.

b1

b2

**Comment by albar965** [comment]
Big improvement. Thank a lot. :+1: 

> If you have something particular in mind for your web presentation, put it forward! I'll see what i can realise.

Moving background while scrolling?

**Comment by u-an-i** [comment]
> Moving background while scrolling?

like this: https://github.com/albar965/albar965.github.io/pull/3 ?

**Pull request merged**
